spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      format_sql: 'true'
      show_sql: 'true'
  eureka:
    instance:
      leaseRenewalIntervalInSeconds: '30'
      hostname: localhost
      client:
        server:
          defaultZone: http://localhost:8761/eureka/
  management:
    endpoints:
      web:
        exposure:
          include: '*'
    tracing:
      sampling:
        probability: '1.0'
  boot:
    message: Message example to test dynamic configuration changes in department service.
      Spring Cloud Bus usage
  logging:
    level:
      org:
        hibernate: DEBUG
        springframework:
          web: DEBUG
          nodeValue: DEBUG
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  datasource:
    password: ${MYSQL_PASSWORD:passwordToFill}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/department_db
  server:
    port: '8080'
