spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:company_database}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:passwordToFill}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  server:
    port: 8080
  eureka:
    instance:
      client:
        server:
          defaultZone: http://localhost:8761/eureka/
      leaseRenewalIntervalInSeconds: 30
      hostname: localhost
  management:
    tracing:
      sampling:
        probability: 1.0
    endpoints:
      web:
        exposure:
          include: "*"
  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    level:
      org.springframework.web: DEBUG
  boot:
    message: "Message example to test dynamic configuration changes in department service. Spring Cloud Bus usage"
