spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/department_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:passwordToFill}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
  server:
    port: '8080'
  boot:
    message: Message example to test dynamic configuration changes in department service.
  rabbitmq:
    password: guest
    port: 5672
    host: localhost
    username: guest  

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        web: DEBUG
        nodeValue: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: '1.0'
