spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/organization_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:passwordToFill}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
  server:
    port: 8083
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      lease-renewal-interval-in-seconds: 30
      hostname: localhost
  management:
    tracing:
      sampling:
        probability: 1.0
    endpoints:
      web:
        exposure:
          include: "*"
  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    level:
      org.springframework.web: DEBUG
  boot:
    message: "Message example to test dynamic configuration changes in department service. Spring Cloud Bus usage"
